language: php
php:
  - '7.2'
  - '7.3'
  - nightly
notifications:
email:
  - jasnapaka@jasnapaka.com
script:
    - phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)